endpoint:
  - https://integbio.jp/rdf/sparql
  - graph:
    - http://refex.dbcls.jp/rdf/fantom5
    - http://refex.dbcls.jp/rdf/genechip
---
endpoint_alt:
  - https://integbio.jp/rdf/sparql
---
endpoint_mirror: https://integbio.jp/rdf/sparql
