- Glycan glycanid:G00054MO:
  - a: 
      - glycan:saccharide
      - glycan:glycan_motif
  - glytoucan:has_primary_id:
      - id: G0054MO
  - rdfs:seeAlso:
      - GlyTouCan_entry_URL: http://glytoucan.org/Structures/Glycans/G00054MO
  - rdfs:label:
      - Glycan_Label: '"Sialyl Lewis X"@en'
  - glycan:has_motif:
      - Glycan_Motif+: glycanid:G00051MO
  - glycan:has_component:
      - Component+: http://rdf.glycoinfo.org/component/1_b-dglc-HEX-1%3A5%7C%7C%282d%3A1%29n-acetyl
  - glycan:has_glycosequence:
      - Glycoct: http://rdf.glycoinfo.org/glycan/G00054MO/glycoct
  - glycan:has_image:
      - Image+: http://www.glytoucan.org/glyspace/service/glycans/G00054MO/image?style=extended&format=png&notation=uoxf-color
  - glycan:has_resource_entry:
      - Resource: http://www.glytoucan.org/Structures/Glycans/G00054MO
  - glytoucan:has_derivatized_mass:
      - MassURI: http://rdf.glycoinfo.org/derivatization_type_none/820.2960859799999

- GlycanMotif glycanid:G00051MO:
  - a: glycan:glycan_motif
  - rdfs:label:
      - Motif_Label: '"Sialyl Lewis X"@en'

- DerivatizedMass <http://rdf.glycoinfo.org/derivatization_type_none/820.2960859799999>:
  - a: glytoucan:derivatized_mass
  - glytoucan:has_derivatization_type:
      - DerivatizationType: glytoucan:Derivatization_type_none
  - glytoucan:has_mass:
      - Mass: '"820.2960859799999"^^xsd:double'

- GlycanImage <http://www.glytoucan.org/glyspace/service/glycans/G00054MO/image?style=extended&format=png&notation=cfg>:
  - a: glycan:image
  - dc:format:
      format: '"image/png"^^xsd:string'
  - glycan:has_symbol_format:
      symbol_format: glycan:symbol_format_cfg

#- ResourceEntry <http://glytoucan.org/Structures/Glycans/G00054MO>:
- ResourceEntry <http://www.glytoucan.org/Structures/Glycans/G00054MO>:
  - a: glycan:resource_entry
  - glycan:n_glycan_database:
      - GlycanDB: glytoucan:database_glytoucan
  - glytoucan:date_registered:
      - Registered: '"2014-10-20 06:47:31.204"^^xsd:dateTimeStamp'
  - glytoucan:contributor:
      - Contributer: http://rdf.glycoinfo.org/glytoucan/contributor/userId/1

- Contributer-name <http://rdf.glycoinfo.org/glytoucan/contributor/userId/1>:
  - a: foaf:Person
  - foaf:name:
      - Name: "Administrator"

- Glycosequence <http://rdf.glycoinfo.org/glycan/G00054MO/glycoct>:
  - a: glycan:glycosequence
  - glycan:has_sequence:
      - Sequence: '"RES 1b:b-dglc-HEX-1:5 2s:n-acetyl 3b:a-lgal-HEX-1:5|6:d 4b:b-dgal-HEX-1:5 5b:a-dgro-dgal-NON-2:6|1:a|2:keto|3:d 6s:n-acetyl LIN 1:1d(2+1)2n 2:1o(3+1)3d 3:1o(4+1)4d 4:4o(3+2)5d 5:5d(5+1)6n"^^xsd:string'
  - glycan:in_carbohydrate_format:
      - CarbohydrateFormat: glycan:carbohydrate_format_glycoct

- Component glycan:has_component:
  - a: glycan:component
  - glycan:has_cardinality:
      - HasCardinality: '"1"^^xsd:integer'
  - glycan:has_monosaccharide:
      - Monosaccharide: http://www.monosaccharidedb.org/rdf/monosaccharide.action?name=b-dgal-HEX-1%3A5

- Monosaccharide-info <http://www.monosaccharidedb.org/rdf/monosaccharide.action?name=b-dgal-HEX-1%3A5>:
  - a: glycan:monosaccharide
  - glycan:has_alias:
      - Alias: http://www.monosaccharidedb.org/rdf/monosaccharide_alias.action?scheme=CARBBANK&name=b-D-Galp

- Alias-info <http://www.monosaccharidedb.org/rdf/monosaccharide_alias.action?scheme=CARBBANK&name=b-D-Galp>:
  - a: glycan:monosaccharide_alias
  - glycan:has_alias_name:
      - AliasName: "b-D-Galp"
  - glycan:has_monosaccharide_notation_scheme:
      - NotationScheme: glycan:monosaccharide_notation_scheme_carbbank
